import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/nav-bar";
import BottomAnimation from "./components/bottom-animation";
import Footer from "./components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      data-theme="ainmhicon"
    >
      <head><meta name="viewport" content="width=device-width, initial-scale=1.0" /></head>

      <body className="min-h-full flex flex-col">
        <NavBar />
        <main className='min-h-[70vh] flex'>
          {children}
        </main>
        <BottomAnimation />
        <Footer />
      </body>
    </html>
  );
}
